/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSubdomainRouteImport } from './routes/s.$subdomain'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiDomainsVerifyRouteImport } from './routes/api/domains/verify'
import { Route as ApiDomainsStatusRouteImport } from './routes/api/domains/status'
import { Route as ApiDomainsRemoveRouteImport } from './routes/api/domains/remove'
import { Route as ApiDomainsAddRouteImport } from './routes/api/domains/add'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSubdomainRoute = SSubdomainRouteImport.update({
  id: '/s/$subdomain',
  path: '/s/$subdomain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiDomainsVerifyRoute = ApiDomainsVerifyRouteImport.update({
  id: '/api/domains/verify',
  path: '/api/domains/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainsStatusRoute = ApiDomainsStatusRouteImport.update({
  id: '/api/domains/status',
  path: '/api/domains/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainsRemoveRoute = ApiDomainsRemoveRouteImport.update({
  id: '/api/domains/remove',
  path: '/api/domains/remove',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDomainsAddRoute = ApiDomainsAddRouteImport.update({
  id: '/api/domains/add',
  path: '/api/domains/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/api/domains/add': typeof ApiDomainsAddRoute
  '/api/domains/remove': typeof ApiDomainsRemoveRoute
  '/api/domains/status': typeof ApiDomainsStatusRoute
  '/api/domains/verify': typeof ApiDomainsVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/api/domains/add': typeof ApiDomainsAddRoute
  '/api/domains/remove': typeof ApiDomainsRemoveRoute
  '/api/domains/status': typeof ApiDomainsStatusRoute
  '/api/domains/verify': typeof ApiDomainsVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate': typeof ApiGenerateRoute
  '/s/$subdomain': typeof SSubdomainRoute
  '/api/domains/add': typeof ApiDomainsAddRoute
  '/api/domains/remove': typeof ApiDomainsRemoveRoute
  '/api/domains/status': typeof ApiDomainsStatusRoute
  '/api/domains/verify': typeof ApiDomainsVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/app'
    | '/dashboard'
    | '/api/chat'
    | '/api/generate'
    | '/s/$subdomain'
    | '/api/domains/add'
    | '/api/domains/remove'
    | '/api/domains/status'
    | '/api/domains/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/app'
    | '/dashboard'
    | '/api/chat'
    | '/api/generate'
    | '/s/$subdomain'
    | '/api/domains/add'
    | '/api/domains/remove'
    | '/api/domains/status'
    | '/api/domains/verify'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/pricing'
    | '/sitemap.xml'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/api/chat'
    | '/api/generate'
    | '/s/$subdomain'
    | '/api/domains/add'
    | '/api/domains/remove'
    | '/api/domains/status'
    | '/api/domains/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  SSubdomainRoute: typeof SSubdomainRoute
  ApiDomainsAddRoute: typeof ApiDomainsAddRoute
  ApiDomainsRemoveRoute: typeof ApiDomainsRemoveRoute
  ApiDomainsStatusRoute: typeof ApiDomainsStatusRoute
  ApiDomainsVerifyRoute: typeof ApiDomainsVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$subdomain': {
      id: '/s/$subdomain'
      path: '/s/$subdomain'
      fullPath: '/s/$subdomain'
      preLoaderRoute: typeof SSubdomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/domains/verify': {
      id: '/api/domains/verify'
      path: '/api/domains/verify'
      fullPath: '/api/domains/verify'
      preLoaderRoute: typeof ApiDomainsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domains/status': {
      id: '/api/domains/status'
      path: '/api/domains/status'
      fullPath: '/api/domains/status'
      preLoaderRoute: typeof ApiDomainsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domains/remove': {
      id: '/api/domains/remove'
      path: '/api/domains/remove'
      fullPath: '/api/domains/remove'
      preLoaderRoute: typeof ApiDomainsRemoveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/domains/add': {
      id: '/api/domains/add'
      path: '/api/domains/add'
      fullPath: '/api/domains/add'
      preLoaderRoute: typeof ApiDomainsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  SSubdomainRoute: SSubdomainRoute,
  ApiDomainsAddRoute: ApiDomainsAddRoute,
  ApiDomainsRemoveRoute: ApiDomainsRemoveRoute,
  ApiDomainsStatusRoute: ApiDomainsStatusRoute,
  ApiDomainsVerifyRoute: ApiDomainsVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
